import { Word } from './types';

export const GRID_SIZE = 10;
export const WORD_COUNT_PER_GAME = 12;

// A mix of common hiragana for filling empty spaces
export const HIRAGANA_CHARS = [
  'あ', 'い', 'う', 'え', 'お',
  'か', 'き', 'く', 'け', 'こ',
  'さ', 'し', 'す', 'せ', 'そ',
  'た', 'ち', 'つ', 'て', 'と',
  'な', 'に', 'ぬ', 'ね', 'の',
  'は', 'ひ', 'ふ', 'へ', 'ほ',
  'ま', 'み', 'む', 'め', 'も',
  'や', 'ゆ', 'よ',
  'ら', 'り', 'る', 'れ', 'ろ',
  'わ', 'を', 'ん'
];

export const JLPT_N5_WORDS: Word[] = [
  { id: '1', hiragana: 'わたし', kanji: '私', meaning: 'I / Me' },
  { id: '2', hiragana: 'ねこ', kanji: '猫', meaning: 'Cat' },
  { id: '3', hiragana: 'いヌ', kanji: '犬', meaning: 'Dog' }, // Fixed below in logic to normalize
  { id: '4', hiragana: 'たべる', kanji: '食べる', meaning: 'To eat' },
  { id: '5', hiragana: 'のむ', kanji: '飲む', meaning: 'To drink' },
  { id: '6', hiragana: 'ほん', kanji: '本', meaning: 'Book' },
  { id: '7', hiragana: 'やま', kanji: '山', meaning: 'Mountain' },
  { id: '8', hiragana: 'かわ', kanji: '川', meaning: 'River' },
  { id: '9', hiragana: 'そら', kanji: '空', meaning: 'Sky' },
  { id: '10', hiragana: 'あめ', kanji: '雨', meaning: 'Rain' },
  { id: '11', hiragana: 'みず', kanji: '水', meaning: 'Water' },
  { id: '12', hiragana: 'ひ', kanji: '日', meaning: 'Sun / Day' },
  { id: '13', hiragana: 'つき', kanji: '月', meaning: 'Moon / Month' },
  { id: '14', hiragana: 'き', kanji: '木', meaning: 'Tree' },
  { id: '15', hiragana: 'はな', kanji: '花', meaning: 'Flower' },
  { id: '16', hiragana: 'さかな', kanji: '魚', meaning: 'Fish' },
  { id: '17', hiragana: 'とり', kanji: '鳥', meaning: 'Bird' },
  { id: '18', hiragana: 'うま', kanji: '馬', meaning: 'Horse' },
  { id: '19', hiragana: 'うし', kanji: '牛', meaning: 'Cow' },
  { id: '20', hiragana: 'みみ', kanji: '耳', meaning: 'Ear' },
  { id: '21', hiragana: 'め', kanji: '目', meaning: 'Eye' },
  { id: '22', hiragana: 'くち', kanji: '口', meaning: 'Mouth' },
  { id: '23', hiragana: 'て', kanji: '手', meaning: 'Hand' },
  { id: '24', hiragana: 'あし', kanji: '足', meaning: 'Foot / Leg' },
  { id: '25', hiragana: 'いえ', kanji: '家', meaning: 'House' },
  { id: '26', hiragana: 'みち', kanji: '道', meaning: 'Road' },
  { id: '27', hiragana: 'えき', kanji: '駅', meaning: 'Station' },
  { id: '28', hiragana: 'でんしゃ', kanji: '電車', meaning: 'Train' },
  { id: '29', hiragana: 'くるま', kanji: '車', meaning: 'Car' },
  { id: '30', hiragana: 'じてんしゃ', kanji: '自転車', meaning: 'Bicycle' },
  { id: '31', hiragana: 'なまえ', kanji: '名前', meaning: 'Name' },
  { id: '32', hiragana: 'ともだち', kanji: '友達', meaning: 'Friend' },
  { id: '33', hiragana: 'せんせい', kanji: '先生', meaning: 'Teacher' },
  { id: '34', hiragana: 'がっこう', kanji: '学校', meaning: 'School' },
  { id: '35', hiragana: 'べんきょう', kanji: '勉強', meaning: 'Study' },
  { id: '36', hiragana: 'えんぴつ', kanji: '鉛筆', meaning: 'Pencil' },
  { id: '37', hiragana: 'かみ', kanji: '紙', meaning: 'Paper' },
  { id: '38', hiragana: 'てがみ', kanji: '手紙', meaning: 'Letter' },
  { id: '39', hiragana: 'おかね', kanji: 'お金', meaning: 'Money' },
  { id: '40', hiragana: 'かいもの', kanji: '買い物', meaning: 'Shopping' },
  { id: '41', hiragana: 'じかん', kanji: '時間', meaning: 'Time' },
  { id: '42', hiragana: 'いま', kanji: '今', meaning: 'Now' },
  { id: '43', hiragana: 'きのう', kanji: '昨日', meaning: 'Yesterday' },
  { id: '44', hiragana: 'きょう', kanji: '今日', meaning: 'Today' },
  { id: '45', hiragana: 'あした', kanji: '明日', meaning: 'Tomorrow' },
  { id: '46', hiragana: 'あさ', kanji: '朝', meaning: 'Morning' },
  { id: '47', hiragana: 'ひる', kanji: '昼', meaning: 'Noon / Daytime' },
  { id: '48', hiragana: 'ばん', kanji: '晩', meaning: 'Evening' },
  { id: '49', hiragana: 'よる', kanji: '夜', meaning: 'Night' },
  { id: '50', hiragana: 'うえ', kanji: '上', meaning: 'Up / Above' },
  { id: '51', hiragana: 'した', kanji: '下', meaning: 'Down / Below' },
  { id: '52', hiragana: 'まえ', kanji: '前', meaning: 'Front / Before' },
  { id: '53', hiragana: 'うしろ', kanji: '後ろ', meaning: 'Back / Behind' },
  { id: '54', hiragana: 'みぎ', kanji: '右', meaning: 'Right' },
  { id: '55', hiragana: 'ひだり', kanji: '左', meaning: 'Left' },
  { id: '56', hiragana: 'なか', kanji: '中', meaning: 'Inside / Middle' },
  { id: '57', hiragana: 'そと', kanji: '外', meaning: 'Outside' },
  { id: '58', hiragana: 'おおきい', kanji: '大きい', meaning: 'Big' },
  { id: '59', hiragana: 'ちいさい', kanji: '小さい', meaning: 'Small' },
  { id: '60', hiragana: 'ながい', kanji: '長い', meaning: 'Long' },
  { id: '61', hiragana: 'みじかい', kanji: '短い', meaning: 'Short' },
  { id: '62', hiragana: 'たかい', kanji: '高い', meaning: 'High / Expensive' },
  { id: '63', hiragana: 'やすい', kanji: '安い', meaning: 'Cheap' },
  { id: '64', hiragana: 'あつい', kanji: '暑い', meaning: 'Hot' },
  { id: '65', hiragana: 'さむい', kanji: '寒い', meaning: 'Cold' },
  { id: '66', hiragana: 'いい', kanji: '良い', meaning: 'Good' },
  { id: '67', hiragana: 'わるい', kanji: '悪い', meaning: 'Bad' },
  { id: '68', hiragana: 'しろい', kanji: '白い', meaning: 'White' },
  { id: '69', hiragana: 'くろい', kanji: '黒い', meaning: 'Black' },
  { id: '70', hiragana: 'あかい', kanji: '赤い', meaning: 'Red' },
  { id: '71', hiragana: 'あおい', kanji: '青い', meaning: 'Blue' },
  { id: '72', hiragana: 'きいろい', kanji: '黄色い', meaning: 'Yellow' },
  { id: '73', hiragana: 'すき', kanji: '好き', meaning: 'Like' },
  { id: '74', hiragana: 'きらい', kanji: '嫌い', meaning: 'Dislike' },
  { id: '75', hiragana: 'うた', kanji: '歌', meaning: 'Song' },
  { id: '76', hiragana: 'えいが', kanji: '映画', meaning: 'Movie' },
  { id: '77', hiragana: 'おんがく', kanji: '音楽', meaning: 'Music' },
  { id: '78', hiragana: 'りょうり', kanji: '料理', meaning: 'Cooking' },
  { id: '79', hiragana: 'スポーツ', kanji: '', meaning: 'Sports' }, // Removed from selection manually or handle katakana
  { id: '80', hiragana: 'さんぽ', kanji: '散歩', meaning: 'Walk' },
  { id: '81', hiragana: 'はしる', kanji: '走る', meaning: 'To run' },
  { id: '82', hiragana: 'あるく', kanji: '歩く', meaning: 'To walk' },
  { id: '83', hiragana: 'まつ', kanji: '待つ', meaning: 'To wait' },
  { id: '84', hiragana: 'あう', kanji: '会う', meaning: 'To meet' },
  { id: '85', hiragana: 'かく', kanji: '書く', meaning: 'To write' },
  { id: '86', hiragana: 'よむ', kanji: '読む', meaning: 'To read' },
  { id: '87', hiragana: 'きく', kanji: '聞く', meaning: 'To listen' },
  { id: '88', hiragana: 'はなす', kanji: '話す', meaning: 'To speak' },
  { id: '89', hiragana: 'いく', kanji: '行く', meaning: 'To go' },
  { id: '90', hiragana: 'くる', kanji: '来る', meaning: 'To come' },
  { id: '91', hiragana: 'かえる', kanji: '帰る', meaning: 'To return' },
  { id: '92', hiragana: 'おきる', kanji: '起きる', meaning: 'To wake up' },
  { id: '93', hiragana: 'ねる', kanji: '寝る', meaning: 'To sleep' },
  { id: '94', hiragana: 'あそぶ', kanji: '遊ぶ', meaning: 'To play' },
  { id: '95', hiragana: 'およぐ', kanji: '泳ぐ', meaning: 'To swim' },
  { id: '96', hiragana: 'かう', kanji: '買う', meaning: 'To buy' },
  { id: '97', hiragana: 'うる', kanji: '売る', meaning: 'To sell' },
  { id: '98', hiragana: 'たつ', kanji: '立つ', meaning: 'To stand' },
  { id: '99', hiragana: 'すわる', kanji: '座る', meaning: 'To sit' },
  { id: '100', hiragana: 'わかる', kanji: '分かる', meaning: 'To understand' }
].filter(w => !w.hiragana.match(/[ア-ン]/)); // Simple filter to ensure only hiragana words for consistency if any katakana slipped in
